version: '3'
services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - WORKER_SERVICE_NAME=worker
      - WORKER_SERVICE_PORT=8082
      - MANAGER_SERVICE_PORT=8081
    networks:
      - my-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    expose:
      - "8082"
    environment:
      - MANAGER_SERVICE_NAME=manager
      - MANAGER_SERVICE_PORT=8081
      - WORKER_SERVICE_PORT=8082
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
