version: '3'
services:
  manager:
    image: openjdk:11-jdk-slim
    volumes:
      - ./manager/build/libs/manager.jar:/manager.jar
    command: ["java -jar /manager.jar"]
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - WORKER_SERVICE_NAME=worker
      - WORKER_SERVICE_PORT=8082
      - MANAGER_SERVICE_PORT=8081
    networks:
      - my-network

  worker:
    image: openjdk:11-jdk-slim
    volumes:
      - ./worker/build/libs/worker.jar:/worker.jar
    command: ["java", "-jar", "/worker.jar"]
    expose:
      - "8082"
    environment:
      - MANAGER_SERVICE_NAME=manager
      - MANAGER_SERVICE_PORT=8081
      - WORKER_SERVICE_PORT=8082
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
