version: '3'
services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - MANAGER_SERVICE_PORT=8081
      - COUNT_WORKERS=2
      - MONGO_URI=mongo:27017,mongodb_secondary_1:27017,mongodb_secondary_2:27017/crack_db?replicaSet=rs0
      - RABBIT_HOST=rabbitmq
    links:
      - mongo
      - mongodb_secondary_1
      - mongodb_secondary_2
      - rabbitmq
    networks:
      - my-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    links:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - my-network

  mongo:
    image: mongo:4.4
    command: bash -c "mongod --replSet rs0 --bind_ip_all  && sleep 15s && ./scripts/init.sh"
    ports:
      - "27017:27017"
    links:
      - mongodb_secondary_1
      - mongodb_secondary_2
    volumes:
      - ~/mongors/data1:/data/db
      - ./init.sh:/scripts/init.sh
    networks:
      - my-network

  mongodb_secondary_1:
    image: mongo:4.4
    container_name: mongodb_secondary_1
    restart: always
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - my-network

  mongodb_secondary_2:
    image: mongo:4.4
    container_name: mongodb_secondary_2
    restart: always
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data: