version: '3'
services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - MANAGER_SERVICE_PORT=8081
      - COUNT_WORKERS=2
      - MONGO_HOST=mongo
      - RABBIT_HOST=rabbitmq
    links:
      - mongo
      - rabbitmq
    networks:
      - my-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    links:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - my-network

  mongo:
    image: mongo:latest
    command: mongod --auth --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: crack_hash_db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data: