version: '3.8'

services:
  mongo:
    image: mongo:4.4
    command: bash -c "mongod --replSet rs0 --bind_ip_all  && sleep 15s && ./scripts/init.sh"
    ports:
      - "27017:27017"
    links:
      - mongodb_secondary_1
      - mongodb_secondary_2
    volumes:
      - ~/mongors/data1:/data/db
      - ./init.sh:/scripts/init.sh

  mongodb_secondary_1:
    image: mongo:4.4
    container_name: mongodb_secondary_1
    restart: always
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - ~/mongors/data2:/data/db

  mongodb_secondary_2:
    image: mongo:4.4
    container_name: mongodb_secondary_2
    restart: always
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - ~/mongors/data3:/data/db